# Generated by Django 4.2.8 on 2023-12-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_active', True), ('workplace__isnull', True), _negated=True), ('is_staff', True), ('is_superuser', True), _connector='OR'), name='active_only_if_workplace_or_admin'),
        ),
    ]
