version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./tech_point:/code
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    env_file:
      - ./.env
