version: "3.8"
name: tech-point

services:
  postgres-db:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  tech-point:
    build: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./tech_point:/code
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
    env_file:
      - ./.env
    depends_on:
      postgres-db:
          condition: service_healthy

volumes:
  postgres-db:
