version: "3.8"
name: tech-point

services:
  postgres-db:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    extends:
      file: common.yaml
      service: app
    command: celery -A core.celery worker -l info
    depends_on:
      - redis

  celery-beat:
    extends:
      file: common.yaml
      service: app
    command: celery -A core.celery beat -l info
    depends_on:
      - redis
      - celery

  tech-point:
    extends:
      file: common.yaml
      service: app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      postgres-db:
        condition: service_healthy
      celery:
        condition: service_started
      celery-beat:
        condition: service_started

volumes:
  postgres-db:
