# Generated by Django 4.2.8 on 2023-12-22 20:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField()),
                ('city', models.CharField()),
                ('street', models.CharField()),
                ('house_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Plant', 'Plant'), ('Distributor', 'Distributor'), ('Dealer center', 'Dealer Center'), ('Retail network', 'Retail Network'), ('Individual entrepreneur', 'Individual Entrepreneur')])),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='supply_chain.address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplyChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplyChainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
                ('debt', models.PositiveIntegerField(default=0)),
                ('parent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='supply_chain.supplychainlink')),
                ('products', models.ManyToManyField(related_name='supply_chain_links', to='supply_chain.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.supplier')),
                ('supply_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='supply_chain.supplychain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='products', to='supply_chain.supplier'),
        ),
    ]
