# Generated by Django 4.2.8 on 2023-12-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplychain',
            name='suppliers',
            field=models.ManyToManyField(related_name='supply_chains', through='supply_chain.SupplyChainLink', to='supply_chain.supplier'),
        ),
    ]
