# Generated by Django 4.2.8 on 2023-12-25 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_alter_supplychainlink_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='suppliers',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='supplychainlink',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='child', to='supply_chain.supplychainlink'),
        ),
        migrations.AddConstraint(
            model_name='supplychainlink',
            constraint=models.UniqueConstraint(fields=('supply_chain', 'level'), name='unique_chain_level'),
        ),
    ]
